### PR TITLE
Added use cases to DG and added logo

### PR DESCRIPTION
**Pull request by krusagiz**
List of Changes:
- Use cases related to `convert`, `tag` and `untag` added to the Developer Guide.
- Logo files added to the repo
- Logo added to Developer Guide and User Guide

_The logo has an alternate version, it will be uploaded as well._

### CODE REVIEW

**Comment by krusagiz** [comment]
Forced pushed the illustrator file out of the branch

**Comment by krusagiz** [comment]
Pulled the latest changes and edited the logos slightly. Developer guide now has an introduction and more definitions in the glossary. HD vector versions of the logos are now included.

**Review by krusagiz — COMMENTED** [review]
Illustrator file has been added back to the repo

**Comment by krusagiz** [comment]
Test cases have been added to the Developer guide

**Review by limerencee — APPROVED** [review]
Thanks for the contribution to the DG! I really dig the new logo 😁

**Pull request merged**
